const ROCKET_CENTER_Y = canvas.height / 2 - 60;

const PLAYER_HIT_THE_ROCKET_POS_X = 20 + ROCKET_WIDTH;
const OPPONENT_HIT_THE_ROCKET_POS_X = canvas.width - ROCKET_WIDTH - BALL_SIDE;

let rocketVY = ROCKET_DEFAULT_VELOCITY_Y;
let ballVX = BALL_DEFAULT_VELOCITY_X;
let ballVY = BALL_DEFAULT_VELOCITY_Y;
